// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221126105802_CreatedUpdatedFeaturesAdded")]
    partial class CreatedUpdatedFeaturesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Identity.IdentityRoleClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.ToTable("RoleClaims", "aid");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("UserRoles", "aid");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ae634538-66a6-4ddf-9583-2a6be072e24d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "7399fd16-8dca-4bdd-b571-0ca051639d44",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPER_ADMIN"
                        });
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "aid");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserLoginEntity", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "aid");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserRoleEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserUserRoles", "aid");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserTokenEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "aid");
                });

            modelBuilder.Entity("Data.Entities.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvertType")
                        .HasColumnType("integer");

                    b.Property<int?>("BathroomNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("BedroomNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<int[]>("ExtraAttributes")
                        .HasColumnType("integer[]");

                    b.Property<int?>("HouseType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int?>("Location")
                        .HasColumnType("integer");

                    b.Property<int?>("Meters")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 2,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 3,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 4,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 5,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 6,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 7,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        },
                        new
                        {
                            Id = 8,
                            AdvertType = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "testtest",
                            District = "District",
                            ExtraAttributes = new[] { 0, 1, 2 },
                            HouseType = 2,
                            IsDeleted = false,
                            IsFeatured = false,
                            Location = 2,
                            Meters = 500,
                            Price = 230000m,
                            Title = "Ev title"
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", "aid");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityRoleClaimEntity", b =>
                {
                    b.HasOne("Data.Entities.Identity.IdentityRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Identity.IdentityRoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserClaimEntity", b =>
                {
                    b.HasOne("Data.Entities.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserLoginEntity", b =>
                {
                    b.HasOne("Data.Entities.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserRoleEntity", b =>
                {
                    b.HasOne("Data.Entities.Identity.IdentityRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Identity.IdentityUserTokenEntity", b =>
                {
                    b.HasOne("Data.Entities.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
